import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Authentication - Next JS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  try {
    if (process.env.ROOT_URL) {
      return (
        <html lang="en" suppressHydrationWarning>
          <body
            className={cn(
              "dark min-h-screen bg-background font-sans antialiased",
              fontSans.variable,
            )}
          >
            {children}
          </body>
        </html>
      );
    }
  } catch (error) {
    throw new Error("Some env variables not set");
  }
}
